"""Leakage-aware learnability certificates for the exact binding algebra.

This module deliberately separates three claims:

* exact passive identifiability on the declared train support;
* finite-sample excitation of a *supplied* shared-prototype model; and
* automatic selection of the sharing law.

Only the first two are computed here.  The finite-sample calculation replays
the exact canonical semantic state and is therefore an oracle-state system-
identification control, not a sequence-only representation-learning result.
The sealed held-out combination is never generated by the accepted splits.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
import hashlib
from itertools import islice
import json
import math
from types import SimpleNamespace
from typing import Iterable, Literal, Sequence

from .algebra_identification import (
    HeldoutIdentificationReport,
    analyze_heldout_identification,
)
from .data import (
    BindingEpisode,
    BindingEventKind,
    BindingTaskConfig,
    generate_binding_episodes,
)
from .exact_algebra import (
    AlgebraAction,
    AlgebraContract,
    BindingAlgebraSpec,
    ConfigLike,
    SemanticState,
    apply_action,
)


SeenSplit = Literal["train", "validation"]
_SEEN_SPLITS = frozenset(("train", "validation"))


def _require_sha256(name: str, value: str) -> None:
    if (
        type(value) is not str
        or len(value) != 64
        or any(character not in "0123456789abcdef" for character in value)
    ):
        raise ValueError(f"{name} must be lowercase SHA-256")


class AlgebraLearningLimitError(RuntimeError):
    """Raised before an analysis exceeds a declared work budget."""


class LearningHypothesis(str, Enum):
    """Hypotheses compared by the Phase-II canonical-state control."""

    UNRESTRICTED_CANONICAL = "unrestricted_canonical_operators"
    KEY_LOCAL_BLOCKS = "key_local_bind_update_copy_query_blocks"
    SHARED_UPDATE_COPY = "shared_update_and_copy_prototypes_only"
    FULL_SHARED_PROTOTYPES = "shared_bind_update_copy_query_prototypes"
    PER_KEY_CYCLIC = "per_key_calibrated_cyclic_bind_query_orbits"
    SHARED_CYCLIC = "shared_calibrated_cyclic_bind_query_orbits"


class CanonicalSupervisionSource(str, Enum):
    """Where canonical pre/post-state table targets came from."""

    EXTERNAL_TRANSITION_RECORD = "external_canonical_transition_record"
    EXACT_EXECUTOR_CONTROL = "sealed_exact_executor_control"


@dataclass(frozen=True)
class HypothesisLearnability:
    hypothesis: LearningHypothesis
    parameter_count: int
    constraint_rank: int
    nullity: int
    heldout_behavior_identified_conditionally: bool
    canonical_state_supervision_assumed: bool
    universal_law_supplied: bool
    sharing_law_selected_from_data: bool

    def __post_init__(self) -> None:
        if type(self.hypothesis) is not LearningHypothesis:
            raise TypeError("hypothesis must be exact LearningHypothesis")
        for name in ("parameter_count", "constraint_rank", "nullity"):
            value = getattr(self, name)
            if type(value) is not int:
                raise TypeError(f"{name} must be an exact integer")
            if value < 0:
                raise ValueError(f"{name} must be nonnegative")
        if self.constraint_rank + self.nullity != self.parameter_count:
            raise ValueError("constraint rank and nullity must partition parameters")
        for name in (
            "heldout_behavior_identified_conditionally",
            "canonical_state_supervision_assumed",
            "universal_law_supplied",
            "sharing_law_selected_from_data",
        ):
            if type(getattr(self, name)) is not bool:
                raise TypeError(f"{name} must be an exact boolean")
        if self.heldout_behavior_identified_conditionally != (self.nullity == 0):
            raise ValueError("conditional identification disagrees with nullity")
        if not self.canonical_state_supervision_assumed:
            raise ValueError("hypothesis certificate assumes canonical-state supervision")
        if self.sharing_law_selected_from_data:
            raise ValueError("hypothesis certificate does not select the sharing law")


@dataclass(frozen=True)
class PrototypeCell:
    """One column of a shared value-block operator."""

    family: str
    transform: int | None
    source_value: int

    def __post_init__(self) -> None:
        if type(self.family) is not str or self.family not in {
            "bind",
            "update",
            "copy",
            "query",
        }:
            raise ValueError("unknown shared prototype family")
        if self.transform is not None and type(self.transform) is not int:
            raise TypeError("transform must be an exact integer or None")
        if type(self.source_value) is not int:
            raise TypeError("source_value must be an exact integer")
        if self.source_value < 0:
            raise ValueError("source_value must be nonnegative")
        if self.family == "update":
            if self.transform is None or self.transform < 0:
                raise ValueError("update cells require a nonnegative transform")
        elif self.transform is not None:
            raise ValueError("only update cells may carry a transform")

    @property
    def label(self) -> str:
        if self.family == "update":
            return f"update:{self.transform}:source:{self.source_value}"
        return f"{self.family}:source:{self.source_value}"


@dataclass(frozen=True)
class SharedPrototypeCoverage:
    """Exact design-rank certificate for one generated seen-only sample."""

    schema: str
    task_fingerprint: str
    split: SeenSplit
    seed: int
    document_count: int
    document_length: int
    event_count: int
    parameter_count: int
    design_rank: int
    nullity: int
    observed_cell_count: int
    total_cell_count: int
    cell_observation_counts: tuple[tuple[str, int], ...]
    cell_event_locations: tuple[tuple[str, int, str, int, int, int, int], ...]
    missing_cells: tuple[str, ...]
    smallest_nonzero_singular_value: float
    largest_singular_value: float
    condition_number: float
    full_rank: bool
    canonical_state_supervision_assumed: bool
    used_heldout_labels_for_fit: bool
    used_heldout_labels_for_selection: bool
    sample_sha256: str

    def __post_init__(self) -> None:
        if self.schema != "tnlm-v3-shared-prototype-coverage-v1":
            raise ValueError("unknown shared-prototype coverage schema")
        _require_sha256("task_fingerprint", self.task_fingerprint)
        _require_sha256("sample_sha256", self.sample_sha256)
        if self.split not in _SEEN_SPLITS:
            raise ValueError("coverage split must be train or validation")
        for name, minimum in (
            ("seed", 0),
            ("document_count", 1),
            ("document_length", 1),
            ("event_count", 1),
            ("parameter_count", 1),
            ("design_rank", 0),
            ("nullity", 0),
            ("observed_cell_count", 1),
            ("total_cell_count", 1),
        ):
            value = getattr(self, name)
            if type(value) is not int:
                raise TypeError(f"{name} must be an exact integer")
            if value < minimum:
                raise ValueError(f"{name} must be at least {minimum}")
        if self.event_count != self.document_count * self.document_length:
            raise ValueError("event count must equal documents times length")
        if self.design_rank + self.nullity != self.parameter_count:
            raise ValueError("design rank and nullity must partition parameters")
        for name in (
            "full_rank",
            "canonical_state_supervision_assumed",
            "used_heldout_labels_for_fit",
            "used_heldout_labels_for_selection",
        ):
            if type(getattr(self, name)) is not bool:
                raise TypeError(f"{name} must be an exact boolean")
        if self.full_rank != (self.design_rank == self.parameter_count):
            raise ValueError("full_rank disagrees with the design rank")
        if not self.canonical_state_supervision_assumed:
            raise ValueError("coverage must declare canonical-state supervision")
        if not isinstance(self.cell_observation_counts, tuple) or not (
            self.cell_observation_counts
        ):
            raise TypeError("cell observation counts must be a nonempty tuple")
        labels: list[str] = []
        for row in self.cell_observation_counts:
            if not isinstance(row, tuple) or len(row) != 2:
                raise TypeError("cell observation counts must be pairs")
            label, count = row
            if type(label) is not str or not label:
                raise ValueError("prototype labels must be nonempty exact strings")
            if type(count) is not int:
                raise TypeError("prototype counts must be exact integers")
            if count < 0:
                raise ValueError("prototype counts must be nonnegative")
            labels.append(label)
        if len(labels) != len(set(labels)):
            raise ValueError("prototype labels must be unique")
        if len(labels) != self.total_cell_count:
            raise ValueError("cell inventory does not match total_cell_count")
        if not isinstance(self.missing_cells, tuple) or any(
            type(label) is not str for label in self.missing_cells
        ):
            raise TypeError("missing_cells must be a tuple of exact strings")
        expected_missing = tuple(
            label for label, count in self.cell_observation_counts if count == 0
        )
        if self.missing_cells != expected_missing:
            raise ValueError("missing cells do not match zero-count cells")
        expected_observed = sum(
            count > 0 for _, count in self.cell_observation_counts
        )
        if self.observed_cell_count != expected_observed:
            raise ValueError("observed_cell_count disagrees with cell counts")
        if self.observed_cell_count + len(self.missing_cells) != self.total_cell_count:
            raise ValueError("observed and missing cells must partition the design")
        if self.parameter_count % self.total_cell_count:
            raise ValueError("parameter count must have a fixed per-cell width")
        cell_width = self.parameter_count // self.total_cell_count
        if self.design_rank != self.observed_cell_count * cell_width:
            raise ValueError("design rank disagrees with observed prototype cells")
        if not isinstance(self.cell_event_locations, tuple):
            raise TypeError("cell event locations must be an exact tuple")
        if len(self.cell_event_locations) != sum(
            count for _, count in self.cell_observation_counts
        ):
            raise ValueError("cell event locations must match observation counts")
        location_counts = {label: 0 for label, _ in self.cell_observation_counts}
        seen_locations: set[tuple[str, int]] = set()
        for row in self.cell_event_locations:
            if not isinstance(row, tuple) or len(row) != 7:
                raise TypeError("cell event locations must be seven-field tuples")
            document_id, event_index, label, *action_fields = row
            if type(document_id) is not str or not document_id:
                raise ValueError("event location document ID must be nonempty")
            if type(event_index) is not int or event_index < 0:
                raise ValueError("event location index must be nonnegative")
            if label not in location_counts:
                raise ValueError("event location names an unknown prototype cell")
            if any(type(value) is not int for value in action_fields):
                raise TypeError("event action fields must be exact integers")
            location = (document_id, event_index)
            if location in seen_locations:
                raise ValueError("event locations must be unique")
            seen_locations.add(location)
            location_counts[label] += 1
        if tuple(location_counts.items()) != self.cell_observation_counts:
            raise ValueError("event locations do not reproduce cell counts")
        if self.used_heldout_labels_for_fit or self.used_heldout_labels_for_selection:
            raise ValueError("seen-only coverage cannot use held-out labels")
        for value in (
            self.smallest_nonzero_singular_value,
            self.largest_singular_value,
            self.condition_number,
        ):
            if type(value) is not float or not math.isfinite(value) or value <= 0.0:
                raise ValueError("singular-value summaries must be positive finite floats")
        if self.smallest_nonzero_singular_value > self.largest_singular_value:
            raise ValueError("singular-value extrema are reversed")
        positive_counts = tuple(
            count for _, count in self.cell_observation_counts if count > 0
        )
        if (
            self.smallest_nonzero_singular_value
            != math.sqrt(float(min(positive_counts)))
            or self.largest_singular_value
            != math.sqrt(float(max(positive_counts)))
        ):
            raise ValueError("singular values disagree with cell observation counts")
        if self.condition_number != (
            self.largest_singular_value / self.smallest_nonzero_singular_value
        ):
            raise ValueError("condition number disagrees with singular values")


@dataclass(frozen=True)
class SharedPrototypeCoverageSweep:
    schema: str
    task_fingerprint: str
    split: SeenSplit
    document_count: int
    document_length: int
    seeds: tuple[int, ...]
    full_rank_count: int
    minimum_rank: int
    maximum_rank: int
    mean_rank: float
    results: tuple[SharedPrototypeCoverage, ...]

    def __post_init__(self) -> None:
        if self.schema != "tnlm-v3-shared-prototype-coverage-sweep-v1":
            raise ValueError("unknown coverage-sweep schema")
        _require_sha256("task_fingerprint", self.task_fingerprint)
        if self.split not in _SEEN_SPLITS:
            raise ValueError("coverage sweep split must be train or validation")
        for name, minimum in (
            ("document_count", 1),
            ("document_length", 1),
            ("full_rank_count", 0),
            ("minimum_rank", 0),
            ("maximum_rank", 0),
        ):
            value = getattr(self, name)
            if type(value) is not int:
                raise TypeError(f"{name} must be an exact integer")
            if value < minimum:
                raise ValueError(f"{name} must be at least {minimum}")
        if not isinstance(self.seeds, tuple) or any(
            type(seed) is not int or seed < 0 for seed in self.seeds
        ):
            raise TypeError("seeds must be a tuple of nonnegative exact integers")
        if len(self.seeds) != len(set(self.seeds)):
            raise ValueError("coverage sweep seeds must be unique")
        if not isinstance(self.results, tuple) or any(
            type(result) is not SharedPrototypeCoverage for result in self.results
        ):
            raise TypeError("results must be a tuple of exact coverage records")
        if not self.seeds or len(self.results) != len(self.seeds):
            raise ValueError("one coverage result is required per seed")
        if tuple(result.seed for result in self.results) != self.seeds:
            raise ValueError("coverage results must follow seed order")
        for result in self.results:
            if result.task_fingerprint != self.task_fingerprint:
                raise ValueError("coverage result task_fingerprint disagrees with sweep")
            if result.split != self.split:
                raise ValueError("coverage result split disagrees with sweep")
            if result.document_count != self.document_count:
                raise ValueError("coverage result document_count disagrees with sweep")
            if result.document_length != self.document_length:
                raise ValueError("coverage result document_length disagrees with sweep")
        if self.full_rank_count != sum(result.full_rank for result in self.results):
            raise ValueError("full-rank count is inconsistent")
        ranks = tuple(result.design_rank for result in self.results)
        if (self.minimum_rank, self.maximum_rank) != (min(ranks), max(ranks)):
            raise ValueError("rank extrema are inconsistent")
        if type(self.mean_rank) is not float or not math.isfinite(self.mean_rank):
            raise ValueError("mean rank must be a finite exact float")
        if self.mean_rank != float(sum(ranks) / len(ranks)):
            raise ValueError("mean rank is inconsistent")


@dataclass(frozen=True)
class CanonicalPrototypeObservation:
    """One independently supplied output column for a prototype cell."""

    task_fingerprint: str
    sample_sha256: str
    split: str
    supervision_source: CanonicalSupervisionSource
    cell_label: str
    target: tuple[int, ...]
    source_document_id: str
    event_index: int
    action_kind: int
    primary_key: int
    secondary_key: int
    argument: int
    pre_state: tuple[int, ...]
    post_state: tuple[int, ...]
    query_target: int | None

    def __post_init__(self) -> None:
        for name in ("task_fingerprint", "sample_sha256"):
            value = getattr(self, name)
            if (
                type(value) is not str
                or len(value) != 64
                or any(character not in "0123456789abcdef" for character in value)
            ):
                raise ValueError(f"{name} must be lowercase SHA-256")
        if self.split != "train":
            raise ValueError("canonical fit observations must use the train split")
        if type(self.supervision_source) is not CanonicalSupervisionSource:
            raise TypeError(
                "supervision_source must be exact CanonicalSupervisionSource"
            )
        if type(self.cell_label) is not str or not self.cell_label:
            raise ValueError("cell_label must be a nonempty exact string")
        if not isinstance(self.target, tuple) or not self.target:
            raise ValueError("target must be a nonempty tuple")
        if any(type(value) is not int for value in self.target):
            raise TypeError("target values must be exact integers")
        if type(self.source_document_id) is not str or not self.source_document_id:
            raise ValueError("source_document_id must be a nonempty exact string")
        if type(self.event_index) is not int or self.event_index < 0:
            raise ValueError("event_index must be an exact nonnegative integer")
        for name in ("action_kind", "primary_key", "secondary_key", "argument"):
            if type(getattr(self, name)) is not int:
                raise TypeError(f"{name} must be an exact integer")
        for name in ("pre_state", "post_state"):
            state = getattr(self, name)
            if not isinstance(state, tuple) or any(
                type(value) is not int for value in state
            ):
                raise TypeError(f"{name} must be a tuple of exact integers")
        if self.query_target is not None and type(self.query_target) is not int:
            raise TypeError("query_target must be an exact integer or None")


@dataclass(frozen=True)
class _PrototypeEstimatorInput:
    """Pure coefficient-estimator input with no task or heldout metadata."""

    value_cardinality: int
    cell_inventory: tuple[str, ...]
    observed_rows: tuple[tuple[str, tuple[int, ...]], ...]


@dataclass(frozen=True)
class LearnedSharedPrototypeTransducer:
    """Tables fit under supplied canonical state and universal key sharing."""

    schema: str
    task_fingerprint: str
    value_cardinality: int
    cell_outputs: tuple[tuple[str, tuple[int, ...] | None], ...]
    coverage: SharedPrototypeCoverage
    observation_sha256: str
    supervision_source: CanonicalSupervisionSource
    canonical_state_supervision_assumed: bool
    universal_key_sharing_supplied: bool
    cyclic_law_supplied: bool
    used_heldout_labels_for_fit: bool
    automatic_hypothesis_selection_performed: bool

    def __post_init__(self) -> None:
        if self.schema != "tnlm-v3-learned-shared-prototype-transducer-v1":
            raise ValueError("unknown learned-prototype schema")
        if type(self.value_cardinality) is not int or self.value_cardinality < 2:
            raise ValueError("value_cardinality must be an exact integer at least two")
        if not isinstance(self.cell_outputs, tuple):
            raise TypeError("cell_outputs must be an exact tuple")
        for row in self.cell_outputs:
            if not isinstance(row, tuple) or len(row) != 2:
                raise TypeError("cell_outputs rows must be exact pairs")
            label, output = row
            if type(label) is not str or not label:
                raise ValueError("cell output labels must be nonempty exact strings")
            if output is not None and not isinstance(output, tuple):
                raise TypeError("prototype outputs must be exact tuples or None")
        labels = tuple(label for label, _ in self.cell_outputs)
        if len(labels) != len(set(labels)):
            raise ValueError("prototype output labels must be unique")
        if type(self.coverage) is not SharedPrototypeCoverage:
            raise TypeError("coverage must be exact SharedPrototypeCoverage")
        if self.task_fingerprint != self.coverage.task_fingerprint:
            raise ValueError("model and coverage task fingerprints must match")
        coverage_labels = tuple(
            label for label, _ in self.coverage.cell_observation_counts
        )
        if labels != coverage_labels:
            raise ValueError("model and coverage cell inventories must match")
        if len(labels) * self.value_cardinality != self.coverage.parameter_count:
            raise ValueError("model width does not match the coverage parameter count")
        missing_outputs = {
            label for label, output in self.cell_outputs if output is None
        }
        if missing_outputs != set(self.coverage.missing_cells):
            raise ValueError("model missing outputs must exactly match coverage")
        if (
            type(self.observation_sha256) is not str
            or len(self.observation_sha256) != 64
            or any(character not in "0123456789abcdef" for character in self.observation_sha256)
        ):
            raise ValueError("observation_sha256 must be lowercase SHA-256")
        for _, output in self.cell_outputs:
            if output is not None:
                if len(output) != self.value_cardinality:
                    raise ValueError("prototype output width is inconsistent")
                if any(type(value) is not int for value in output):
                    raise TypeError("prototype outputs must be exact integers")
                if any(value not in (0, 1) for value in output) or sum(output) != 1:
                    raise ValueError("prototype outputs must be one-hot")
        for name in (
            "canonical_state_supervision_assumed",
            "universal_key_sharing_supplied",
            "cyclic_law_supplied",
            "used_heldout_labels_for_fit",
            "automatic_hypothesis_selection_performed",
        ):
            if type(getattr(self, name)) is not bool:
                raise TypeError(f"{name} must be an exact boolean")
        if not self.canonical_state_supervision_assumed:
            raise ValueError("this learner is explicitly canonical-state supervised")
        if type(self.supervision_source) is not CanonicalSupervisionSource:
            raise TypeError("supervision_source must be exact CanonicalSupervisionSource")
        if not self.universal_key_sharing_supplied:
            raise ValueError("this learner explicitly supplies universal key sharing")
        if self.cyclic_law_supplied:
            raise ValueError("the shared-prototype learner must fit, not supply, C_V")
        if self.used_heldout_labels_for_fit:
            raise ValueError("the shared-prototype learner is seen-only")
        if self.automatic_hypothesis_selection_performed:
            raise ValueError("the shared-prototype learner does not select sharing")


@dataclass(frozen=True)
class SharedPrototypeFitEvaluation:
    schema: str
    evaluated_cell_count: int
    exact_cell_count: int
    missing_cell_count: int
    all_value_tables_exact: bool
    all_valid_programs_exact_given_supplied_state_contract: bool
    heldout_semantics_used_only_for_postfit_evaluation: bool

    def __post_init__(self) -> None:
        if self.schema != "tnlm-v3-shared-prototype-fit-evaluation-v1":
            raise ValueError("unknown prototype-fit evaluation schema")
        for name in (
            "evaluated_cell_count",
            "exact_cell_count",
            "missing_cell_count",
        ):
            value = getattr(self, name)
            if type(value) is not int:
                raise TypeError(f"{name} must be an exact integer")
            if value < 0:
                raise ValueError(f"{name} must be nonnegative")
        for name in (
            "all_value_tables_exact",
            "all_valid_programs_exact_given_supplied_state_contract",
            "heldout_semantics_used_only_for_postfit_evaluation",
        ):
            if type(getattr(self, name)) is not bool:
                raise TypeError(f"{name} must be an exact boolean")
        if self.exact_cell_count + self.missing_cell_count > self.evaluated_cell_count:
            raise ValueError("prototype-fit counts are inconsistent")
        if self.all_value_tables_exact != (
            self.exact_cell_count == self.evaluated_cell_count
        ):
            raise ValueError("all_value_tables_exact is inconsistent")
        if self.all_valid_programs_exact_given_supplied_state_contract != (
            self.all_value_tables_exact
        ):
            raise ValueError("program exactness must follow exact closed tables")
        if not self.heldout_semantics_used_only_for_postfit_evaluation:
            raise ValueError("postfit evaluation must be explicitly labelled")


@dataclass(frozen=True)
class PseudoheldoutFoldCertificate:
    real_heldout_pair: tuple[int, int]
    pseudoheldout_pair: tuple[int, int]
    supplied_shared_parameter_count: int
    supplied_shared_design_rank: int
    supplied_shared_nullity: int
    supplied_shared_identifies_pseudoheldout: bool
    automatic_hypothesis_selection_performed: bool

    def __post_init__(self) -> None:
        for name in ("real_heldout_pair", "pseudoheldout_pair"):
            pair = getattr(self, name)
            if (
                not isinstance(pair, tuple)
                or len(pair) != 2
                or any(type(value) is not int or value < 0 for value in pair)
            ):
                raise ValueError(f"{name} must be a pair of nonnegative exact integers")
        if self.real_heldout_pair == self.pseudoheldout_pair:
            raise ValueError("pseudoheldout pair must differ from the real heldout pair")
        for name in (
            "supplied_shared_parameter_count",
            "supplied_shared_design_rank",
            "supplied_shared_nullity",
        ):
            value = getattr(self, name)
            if type(value) is not int:
                raise TypeError(f"{name} must be an exact integer")
            if value < 0:
                raise ValueError(f"{name} must be nonnegative")
        if self.supplied_shared_parameter_count == 0:
            raise ValueError("pseudoheldout parameter count must be positive")
        for name in (
            "supplied_shared_identifies_pseudoheldout",
            "automatic_hypothesis_selection_performed",
        ):
            if type(getattr(self, name)) is not bool:
                raise TypeError(f"{name} must be an exact boolean")
        if self.supplied_shared_design_rank + self.supplied_shared_nullity != (
            self.supplied_shared_parameter_count
        ):
            raise ValueError("pseudoheldout rank and nullity are inconsistent")
        if self.supplied_shared_identifies_pseudoheldout != (
            self.supplied_shared_nullity == 0
        ):
            raise ValueError("pseudoheldout identification disagrees with nullity")
        if self.automatic_hypothesis_selection_performed:
            raise ValueError("this certificate does not perform hypothesis selection")


@dataclass(frozen=True)
class AlgebraLearnabilityReport:
    schema: str
    task_fingerprint: str
    heldout_pair: tuple[int, int]
    full_state_count: int
    train_state_count: int
    full_feature_rank: int
    train_feature_rank: int
    passive_unrestricted_nullity: int
    passive_uniform_recovery_possible: bool
    zero_support_identical_likelihood_witness_exists: bool
    one_separating_membership_probe: tuple[str, ...]
    hypotheses: tuple[HypothesisLearnability, ...]
    pseudoheldout_folds: tuple[PseudoheldoutFoldCertificate, ...]
    automatic_hypothesis_selection_performed: bool
    sequence_only_representation_learning_performed: bool
    report_sha256: str

    def __post_init__(self) -> None:
        if self.schema != "tnlm-v3-algebra-learnability-v1":
            raise ValueError("unknown algebra-learnability schema")
        _require_sha256("task_fingerprint", self.task_fingerprint)
        _require_sha256("report_sha256", self.report_sha256)
        if (
            not isinstance(self.heldout_pair, tuple)
            or len(self.heldout_pair) != 2
            or any(type(value) is not int or value < 0 for value in self.heldout_pair)
        ):
            raise ValueError("heldout_pair must contain nonnegative exact integers")
        for name in (
            "full_state_count",
            "train_state_count",
            "full_feature_rank",
            "train_feature_rank",
            "passive_unrestricted_nullity",
        ):
            value = getattr(self, name)
            if type(value) is not int:
                raise TypeError(f"{name} must be an exact integer")
            if value < 0:
                raise ValueError(f"{name} must be nonnegative")
        if self.full_state_count <= self.train_state_count:
            raise ValueError("full_state_count must exceed train_state_count")
        if self.full_feature_rank <= self.train_feature_rank:
            raise ValueError("full_feature_rank must exceed train_feature_rank")
        if self.passive_unrestricted_nullity <= 0:
            raise ValueError("passive unrestricted nullity must be positive")
        for name in (
            "passive_uniform_recovery_possible",
            "zero_support_identical_likelihood_witness_exists",
            "automatic_hypothesis_selection_performed",
            "sequence_only_representation_learning_performed",
        ):
            if type(getattr(self, name)) is not bool:
                raise TypeError(f"{name} must be an exact boolean")
        if not isinstance(self.one_separating_membership_probe, tuple) or any(
            type(event) is not str or not event
            for event in self.one_separating_membership_probe
        ):
            raise TypeError("membership probe must be a tuple of nonempty strings")
        if not self.one_separating_membership_probe:
            raise ValueError("membership probe cannot be empty")
        if not isinstance(self.hypotheses, tuple) or any(
            type(row) is not HypothesisLearnability for row in self.hypotheses
        ):
            raise TypeError("hypotheses must be exact hypothesis certificates")
        hypothesis_names = tuple(row.hypothesis for row in self.hypotheses)
        if hypothesis_names != tuple(LearningHypothesis):
            raise ValueError("hypothesis certificates must contain the exact ladder")
        if (
            self.passive_unrestricted_nullity
            != self.hypotheses[0].nullity
        ):
            raise ValueError(
                "passive unrestricted nullity disagrees with its hypothesis row"
            )
        if not isinstance(self.pseudoheldout_folds, tuple) or any(
            type(row) is not PseudoheldoutFoldCertificate
            for row in self.pseudoheldout_folds
        ):
            raise TypeError("pseudoheldout folds must be exact certificates")
        if not self.pseudoheldout_folds:
            raise ValueError("pseudoheldout fold inventory cannot be empty")
        pseudo_pairs = tuple(row.pseudoheldout_pair for row in self.pseudoheldout_folds)
        if len(pseudo_pairs) != len(set(pseudo_pairs)):
            raise ValueError("pseudoheldout folds must be unique")
        if any(
            row.real_heldout_pair != self.heldout_pair
            for row in self.pseudoheldout_folds
        ):
            raise ValueError("pseudoheldout folds disagree on the real heldout pair")
        if self.passive_uniform_recovery_possible:
            raise ValueError("unrestricted passive recovery is impossible on zero support")
        if not self.zero_support_identical_likelihood_witness_exists:
            raise ValueError("the report requires the exact Phase-I witness")
        if self.automatic_hypothesis_selection_performed:
            raise ValueError("this report does not select a hypothesis")
        if self.sequence_only_representation_learning_performed:
            raise ValueError("this report is an oracle-state analysis")
        expected_sha256 = hashlib.sha256(
            json.dumps(
                _report_payload(self), sort_keys=True, separators=(",", ":")
            ).encode("utf-8")
        ).hexdigest()
        if self.report_sha256 != expected_sha256:
            raise ValueError("report_sha256 does not bind the canonical report")


def _spec(config: ConfigLike) -> BindingAlgebraSpec:
    if type(config) is BindingAlgebraSpec:
        return config
    if type(config) is BindingTaskConfig:
        return BindingAlgebraSpec.from_task(config)
    raise TypeError("config must be exact BindingAlgebraSpec or BindingTaskConfig")


def _task_fingerprint(config: ConfigLike) -> str:
    if type(config) is BindingTaskConfig:
        return config.fingerprint()
    spec = _spec(config)
    material = json.dumps(
        {
            "domain": "tnlm-v3-binding-algebra-spec-v1",
            "num_surface_keys": spec.num_surface_keys,
            "value_cardinality": spec.value_cardinality,
            "max_live_bindings": spec.max_live_bindings,
            "heldout_key_value_pairs": [
                list(pair) for pair in spec.heldout_key_value_pairs
            ],
            "branches": spec.branches,
        },
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return hashlib.sha256(material).hexdigest()


def _plain_int(name: str, value: int, minimum: int) -> int:
    if type(value) is not int:
        raise TypeError(f"{name} must be an exact integer")
    if value < minimum:
        raise ValueError(f"{name} must be at least {minimum}")
    return value


def shared_prototype_cells(config: ConfigLike) -> tuple[PrototypeCell, ...]:
    """Return the canonical 24 value-block columns for the screen task."""

    spec = _spec(config)
    values = spec.value_cardinality
    result: list[PrototypeCell] = []
    result.extend(PrototypeCell("bind", None, value) for value in range(values))
    result.extend(
        PrototypeCell("update", transform, source)
        for transform in range(values - 1)
        for source in range(values)
    )
    result.extend(PrototypeCell("copy", None, value) for value in range(values))
    result.extend(PrototypeCell("query", None, value) for value in range(values))
    return tuple(result)


def shared_prototype_parameter_count(config: ConfigLike) -> int:
    spec = _spec(config)
    values = spec.value_cardinality
    return (values * values + 2 * values) * values


def _episode_action(episode: BindingEpisode, index: int) -> AlgebraAction:
    return AlgebraAction(
        kind=BindingEventKind(int(episode.inputs.event_kinds[index])),
        primary_key=int(episode.inputs.primary_key_ids[index]) - 1,
        secondary_key=int(episode.inputs.secondary_key_ids[index]) - 1,
        argument=int(episode.inputs.arguments[index]) - 1,
    )


def _visible_episode_payload(episode: BindingEpisode) -> dict[str, object]:
    inputs = episode.inputs
    return {
        "document_id": episode.document_id,
        "generation_seed": episode.generation_seed,
        "config_fingerprint": episode.config_fingerprint,
        "split": episode.split,
        "length": episode.length,
        "token_ids": inputs.token_ids.tolist(),
        "event_kinds": inputs.event_kinds.tolist(),
        "primary_key_ids": inputs.primary_key_ids.tolist(),
        "secondary_key_ids": inputs.secondary_key_ids.tolist(),
        "arguments": inputs.arguments.tolist(),
        "valid_mask": inputs.valid_mask.tolist(),
    }


def _visible_episode_equal(left: BindingEpisode, right: BindingEpisode) -> bool:
    return _visible_episode_payload(left) == _visible_episode_payload(right)


def _observed_cell(state: SemanticState, action: AlgebraAction) -> PrototypeCell | None:
    if action.kind is BindingEventKind.BIND:
        return PrototypeCell("bind", None, action.argument)
    if action.kind is BindingEventKind.UPDATE:
        return PrototypeCell("update", action.argument, state.values[action.primary_key])
    if action.kind is BindingEventKind.COPY:
        return PrototypeCell("copy", None, state.values[action.secondary_key])
    if action.kind is BindingEventKind.QUERY:
        return PrototypeCell("query", None, state.values[action.primary_key])
    return None


def _one_hot(value: int, width: int) -> tuple[int, ...]:
    return tuple(int(index == value) for index in range(width))


def _cell_target(
    spec: BindingAlgebraSpec,
    state: SemanticState,
    action: AlgebraAction,
    successor: SemanticState,
    query_target: int | None,
) -> tuple[int, ...] | None:
    cell = _observed_cell(state, action)
    if cell is None:
        return None
    if action.kind is BindingEventKind.QUERY:
        if query_target is None:
            raise ValueError("query cell lacks a target")
        value = query_target
    else:
        value = successor.values[action.primary_key]
    if not 0 <= value < spec.value_cardinality:
        raise ValueError("prototype target is outside the value vocabulary")
    return _one_hot(value, spec.value_cardinality)


def shared_prototype_coverage_from_episodes(
    config: BindingTaskConfig,
    episodes: Sequence[BindingEpisode],
    *,
    split: SeenSplit,
    seed: int,
    document_length: int,
    max_events: int = 1_000_000,
) -> SharedPrototypeCoverage:
    """Measure canonical-state prototype excitation in supplied episodes.

    The replay state is audit-only supervision.  Evaluation fields such as
    heldout masks, oracle routes, parents, and generations are not consulted.
    """

    if type(config) is not BindingTaskConfig:
        raise TypeError("config must be exact BindingTaskConfig")
    spec = _spec(config)
    if split not in _SEEN_SPLITS:
        raise ValueError("split must be train or validation")
    _plain_int("seed", seed, 0)
    _plain_int("document_length", document_length, 1)
    _plain_int("max_events", max_events, 1)
    if not isinstance(episodes, Sequence) or not episodes:
        raise ValueError("episodes must be a nonempty sequence")
    if len(episodes) * document_length > max_events:
        raise AlgebraLearningLimitError("episode replay exceeds max_events")
    episodes = tuple(episodes)
    if any(type(episode) is not BindingEpisode for episode in episodes):
        raise TypeError("episodes must contain exact BindingEpisode values")
    if any(
        episode.config_fingerprint != config.fingerprint() for episode in episodes
    ):
        raise ValueError("every episode must bind the exact task fingerprint")
    if any(episode.split != split for episode in episodes):
        raise ValueError("every episode must use the declared seen-only split")
    if any(episode.length != document_length for episode in episodes):
        raise ValueError("every episode must have the declared document length")
    event_count = sum(episode.length for episode in episodes)
    if event_count > max_events:
        raise AlgebraLearningLimitError("episode replay exceeds max_events")
    expected_episodes = generate_binding_episodes(
        config,
        count=len(episodes),
        seed=seed,
        split=split,
        lengths=(document_length,) * len(episodes),
    )
    if any(
        not _visible_episode_equal(actual, expected)
        for actual, expected in zip(episodes, expected_episodes, strict=True)
    ):
        raise ValueError("episodes do not match the declared deterministic sample")

    all_cells = shared_prototype_cells(spec)
    counts = {cell: 0 for cell in all_cells}
    event_locations: list[tuple[str, int, str, int, int, int, int]] = []
    digest_rows: list[dict[str, object]] = []
    for episode in episodes:
        state = SemanticState((-1,) * spec.num_surface_keys)
        digest_rows.append(_visible_episode_payload(episode))
        for index in range(episode.length):
            if not bool(episode.inputs.valid_mask[index]):
                raise ValueError("un-padded episodes cannot contain invalid events")
            action = _episode_action(episode, index)
            if any(
                state.values[key] == value
                for key, value in spec.heldout_key_value_pairs
            ):
                raise ValueError("seen-only replay entered a held-out state")
            cell = _observed_cell(state, action)
            if cell is not None:
                if cell not in counts:
                    raise ValueError("episode exposes an unsupported prototype cell")
                counts[cell] += 1
                event_locations.append(
                    (
                        episode.document_id,
                        index,
                        cell.label,
                        int(action.kind),
                        action.primary_key,
                        action.secondary_key,
                        action.argument,
                    )
                )
            result = apply_action(spec, state, action, contract=AlgebraContract.STRICT)
            if not result.defined or result.state is None:
                raise ValueError("generated episode violates the strict algebra")
            state = result.state
            if any(
                state.values[key] == value
                for key, value in spec.heldout_key_value_pairs
            ):
                raise ValueError("seen-only replay entered a held-out state")

    observed = tuple(cell for cell in all_cells if counts[cell] > 0)
    missing = tuple(cell for cell in all_cells if counts[cell] == 0)
    values = spec.value_cardinality
    parameter_count = len(all_cells) * values
    design_rank = len(observed) * values
    positive_counts = tuple(counts[cell] for cell in observed)
    smallest = math.sqrt(float(min(positive_counts)))
    largest = math.sqrt(float(max(positive_counts)))
    material = json.dumps(
        {
            "domain": "tnlm-v3-shared-prototype-sample-v1",
            "task": _task_fingerprint(config),
            "split": split,
            "seed": seed,
            "visible_episodes": digest_rows,
            "counts": [(cell.label, counts[cell]) for cell in all_cells],
        },
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return SharedPrototypeCoverage(
        schema="tnlm-v3-shared-prototype-coverage-v1",
        task_fingerprint=_task_fingerprint(config),
        split=split,
        seed=seed,
        document_count=len(episodes),
        document_length=document_length,
        event_count=event_count,
        parameter_count=parameter_count,
        design_rank=design_rank,
        nullity=parameter_count - design_rank,
        observed_cell_count=len(observed),
        total_cell_count=len(all_cells),
        cell_observation_counts=tuple(
            (cell.label, counts[cell]) for cell in all_cells
        ),
        cell_event_locations=tuple(event_locations),
        missing_cells=tuple(cell.label for cell in missing),
        smallest_nonzero_singular_value=float(smallest),
        largest_singular_value=float(largest),
        condition_number=float(largest / smallest),
        full_rank=design_rank == parameter_count,
        canonical_state_supervision_assumed=True,
        used_heldout_labels_for_fit=False,
        used_heldout_labels_for_selection=False,
        sample_sha256=hashlib.sha256(material).hexdigest(),
    )


def generate_shared_prototype_coverage(
    config: BindingTaskConfig,
    *,
    split: SeenSplit,
    seed: int,
    document_count: int,
    document_length: int,
    max_events: int = 1_000_000,
) -> SharedPrototypeCoverage:
    """Generate a seen-only sample and return its exact prototype rank."""

    if type(config) is not BindingTaskConfig:
        raise TypeError("config must be exact BindingTaskConfig")
    if split not in _SEEN_SPLITS:
        raise ValueError("split must be train or validation")
    _plain_int("seed", seed, 0)
    _plain_int("document_count", document_count, 1)
    _plain_int("document_length", document_length, config.min_length)
    _plain_int("max_events", max_events, 1)
    if document_length > config.max_length:
        raise ValueError("document_length exceeds config.max_length")
    if document_count * document_length > max_events:
        raise AlgebraLearningLimitError("requested sample exceeds max_events")
    episodes = generate_binding_episodes(
        config,
        count=document_count,
        seed=seed,
        split=split,
        lengths=(document_length,) * document_count,
    )
    return shared_prototype_coverage_from_episodes(
        config,
        episodes,
        split=split,
        seed=seed,
        document_length=document_length,
        max_events=max_events,
    )


def _oracle_observations_from_validated_episodes(
    config: BindingTaskConfig,
    episodes: Sequence[BindingEpisode],
    coverage: SharedPrototypeCoverage,
) -> tuple[CanonicalPrototypeObservation, ...]:
    spec = _spec(config)
    if coverage.task_fingerprint != config.fingerprint():
        raise ValueError("coverage task fingerprint does not match the task")
    if coverage.split != "train":
        raise ValueError("oracle coefficient control requires the train split")
    observations: list[CanonicalPrototypeObservation] = []
    for episode in episodes:
        state = SemanticState((-1,) * spec.num_surface_keys)
        for index in range(episode.length):
            action = _episode_action(episode, index)
            result = apply_action(spec, state, action, contract=AlgebraContract.STRICT)
            if not result.defined or result.state is None:
                raise ValueError("generated episode violates the strict algebra")
            cell = _observed_cell(state, action)
            target = _cell_target(
                spec,
                state,
                action,
                result.state,
                result.query_target,
            )
            if cell is not None:
                if target is None:
                    raise AssertionError("prototype cell lost its target")
                observations.append(
                    CanonicalPrototypeObservation(
                        task_fingerprint=config.fingerprint(),
                        sample_sha256=coverage.sample_sha256,
                        split="train",
                        supervision_source=(
                            CanonicalSupervisionSource.EXACT_EXECUTOR_CONTROL
                        ),
                        cell_label=cell.label,
                        target=target,
                        source_document_id=episode.document_id,
                        event_index=index,
                        action_kind=int(action.kind),
                        primary_key=action.primary_key,
                        secondary_key=action.secondary_key,
                        argument=action.argument,
                        pre_state=state.values,
                        post_state=result.state.values,
                        query_target=result.query_target,
                    )
                )
            state = result.state
    return tuple(observations)


def oracle_canonical_observations_from_episodes(
    config: BindingTaskConfig,
    episodes: Sequence[BindingEpisode],
    *,
    split: SeenSplit,
    seed: int,
    document_length: int,
    max_events: int = 1_000_000,
) -> tuple[CanonicalPrototypeObservation, ...]:
    """Create an explicitly circular exact-executor optimization control.

    These targets are *not* empirical sequence supervision.  The function is
    public and marks every returned row as an exact-executor control, so its
    unmodified artifacts cannot enter the external-record fit path.  This is
    an entry-path attestation, not cryptographic origin authentication.
    """

    coverage = shared_prototype_coverage_from_episodes(
        config,
        episodes,
        split=split,
        seed=seed,
        document_length=document_length,
        max_events=max_events,
    )
    return _oracle_observations_from_validated_episodes(
        config,
        episodes,
        coverage,
    )


def _validate_canonical_prototype_observations(
    config: BindingTaskConfig,
    observations: Sequence[CanonicalPrototypeObservation],
    *,
    coverage: SharedPrototypeCoverage,
    expected_supervision_source: CanonicalSupervisionSource,
) -> tuple[_PrototypeEstimatorInput, str]:
    """Validate provenance and remove sealed-cell metadata before fitting.

    This trusted firewall sees the full task solely to reject contamination.
    The returned estimator input contains dimensions and sanitized observed
    `(cell_label, target)` rows, but no held-out pair identifier.
    """

    if type(config) is not BindingTaskConfig:
        raise TypeError("config must be exact BindingTaskConfig")
    if type(coverage) is not SharedPrototypeCoverage:
        raise TypeError("coverage must be exact SharedPrototypeCoverage")
    if coverage.task_fingerprint != config.fingerprint():
        raise ValueError("coverage task fingerprint does not match the task")
    if coverage.split != "train":
        raise ValueError("coefficient fitting requires the direct train split")
    if type(expected_supervision_source) is not CanonicalSupervisionSource:
        raise TypeError(
            "expected_supervision_source must be exact CanonicalSupervisionSource"
        )
    if not isinstance(observations, Sequence) or not observations:
        raise ValueError("observations must be a nonempty sequence")
    if len(observations) != len(coverage.cell_event_locations):
        raise ValueError("canonical observations must match the sample inventory")
    observations = tuple(observations)
    if any(type(row) is not CanonicalPrototypeObservation for row in observations):
        raise TypeError("observations must contain exact canonical records")
    spec = _spec(config)
    cells = shared_prototype_cells(spec)
    by_label = {cell.label: cell for cell in cells}
    expected_counts = dict(coverage.cell_observation_counts)
    observed_counts = {label: 0 for label in expected_counts}
    expected_locations = {
        (document_id, event_index): (
            label,
            action_kind,
            primary_key,
            secondary_key,
            argument,
        )
        for (
            document_id,
            event_index,
            label,
            action_kind,
            primary_key,
            secondary_key,
            argument,
        ) in coverage.cell_event_locations
    }
    source_locations: set[tuple[str, int]] = set()
    for observation in observations:
        if observation.task_fingerprint != config.fingerprint():
            raise ValueError("observation task fingerprint does not match the task")
        if observation.sample_sha256 != coverage.sample_sha256:
            raise ValueError("observation sample digest does not match coverage")
        if observation.split != "train":
            raise ValueError("coefficient observations must use the train split")
        if observation.supervision_source is not expected_supervision_source:
            raise ValueError("observation provenance does not match the fit entry path")
        cell = by_label.get(observation.cell_label)
        if cell is None:
            raise ValueError("observation names an unknown prototype cell")
        if len(observation.target) != spec.value_cardinality:
            raise ValueError("observation target width does not match the task")
        if any(value not in (0, 1) for value in observation.target) or sum(
            observation.target
        ) != 1:
            raise ValueError("canonical prototype targets must be one-hot")
        location = (observation.source_document_id, observation.event_index)
        if location in source_locations:
            raise ValueError("canonical observations cannot duplicate an event")
        expected_location = expected_locations.get(location)
        supplied_location = (
            observation.cell_label,
            observation.action_kind,
            observation.primary_key,
            observation.secondary_key,
            observation.argument,
        )
        if expected_location != supplied_location:
            raise ValueError("canonical observation is not bound to its sample event")
        source_locations.add(location)

        for state_name in ("pre_state", "post_state"):
            state_values = getattr(observation, state_name)
            if len(state_values) != spec.num_surface_keys:
                raise ValueError(f"{state_name} width does not match the task")
            if any(
                value < -1 or value >= spec.value_cardinality
                for value in state_values
            ):
                raise ValueError(f"{state_name} contains an invalid value")
            if sum(value >= 0 for value in state_values) > spec.max_live_bindings:
                raise ValueError(f"{state_name} exceeds the live-binding cap")
            if any(
                state_values[key] == value
                for key, value in spec.heldout_key_value_pairs
            ):
                raise ValueError(f"{state_name} contains a held-out pair")

        try:
            action = AlgebraAction(
                kind=BindingEventKind(observation.action_kind),
                primary_key=observation.primary_key,
                secondary_key=observation.secondary_key,
                argument=observation.argument,
            )
        except (TypeError, ValueError) as error:
            raise ValueError("observation contains an invalid action") from error
        pre_state = SemanticState(observation.pre_state)
        post_state = SemanticState(observation.post_state)
        if _observed_cell(pre_state, action) != cell:
            raise ValueError("observation cell disagrees with its pre-state and action")
        if action.kind is BindingEventKind.BIND:
            if pre_state.values[action.primary_key] != -1:
                raise ValueError("bind observations require an inactive destination")
        elif action.kind is BindingEventKind.UPDATE:
            if pre_state.values[action.primary_key] < 0:
                raise ValueError("update observations require an active key")
        elif action.kind is BindingEventKind.COPY:
            if action.primary_key == action.secondary_key:
                raise ValueError("copy observations require distinct keys")
            if (
                pre_state.values[action.primary_key] < 0
                or pre_state.values[action.secondary_key] < 0
            ):
                raise ValueError("copy observations require two active keys")
        for key in range(spec.num_surface_keys):
            if key != action.primary_key and (
                pre_state.values[key] != post_state.values[key]
            ):
                raise ValueError("prototype observations may change only the primary key")
        if action.kind is BindingEventKind.QUERY:
            if post_state != pre_state:
                raise ValueError("query observations must preserve semantic state")
            if observation.query_target is None:
                raise ValueError("query observations must carry a categorical target")
        elif observation.query_target is not None:
            raise ValueError("only query observations may carry query_target")
        observed_target = _cell_target(
            spec,
            pre_state,
            action,
            post_state,
            observation.query_target,
        )
        if observed_target != observation.target:
            raise ValueError("observation target disagrees with its supplied states")
        observed_counts[cell.label] += 1
    if observed_counts != expected_counts:
        raise ValueError("canonical observations do not match the coverage counts")
    if source_locations != set(expected_locations):
        raise ValueError("canonical observations do not cover the sample events")
    observation_material = json.dumps(
        [
            {
                "cell_label": row.cell_label,
                "target": list(row.target),
                "source_document_id": row.source_document_id,
                "event_index": row.event_index,
                "task_fingerprint": row.task_fingerprint,
                "sample_sha256": row.sample_sha256,
                "split": row.split,
                "supervision_source": row.supervision_source.value,
                "action_kind": row.action_kind,
                "primary_key": row.primary_key,
                "secondary_key": row.secondary_key,
                "argument": row.argument,
                "pre_state": list(row.pre_state),
                "post_state": list(row.post_state),
                "query_target": row.query_target,
            }
            for row in observations
        ],
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return (
        _PrototypeEstimatorInput(
            value_cardinality=spec.value_cardinality,
            cell_inventory=tuple(cell.label for cell in cells),
            observed_rows=tuple(
                (observation.cell_label, observation.target)
                for observation in observations
            ),
        ),
        hashlib.sha256(observation_material).hexdigest(),
    )


def _estimate_shared_prototype_outputs(
    batch: _PrototypeEstimatorInput,
) -> tuple[tuple[str, tuple[int, ...] | None], ...]:
    """Estimate shared tables without access to the sealed-cell identifier."""

    if type(batch) is not _PrototypeEstimatorInput:
        raise TypeError("batch must be exact prototype estimator input")
    outputs: dict[str, tuple[int, ...] | None] = {
        label: None for label in batch.cell_inventory
    }
    for label, target in batch.observed_rows:
        if label not in outputs:
            raise ValueError("validated row names an unknown prototype cell")
        previous = outputs[label]
        if previous is not None and previous != target:
            raise ValueError("shared prototype observations are inconsistent")
        outputs[label] = target
    return tuple((label, outputs[label]) for label in batch.cell_inventory)


def _fit_shared_prototype_transducer_with_source(
    config: BindingTaskConfig,
    observations: Sequence[CanonicalPrototypeObservation],
    *,
    coverage: SharedPrototypeCoverage,
    supervision_source: CanonicalSupervisionSource,
) -> LearnedSharedPrototypeTransducer:
    estimator_input, observation_sha256 = (
        _validate_canonical_prototype_observations(
            config,
            observations,
            coverage=coverage,
            expected_supervision_source=supervision_source,
        )
    )
    cell_outputs = _estimate_shared_prototype_outputs(estimator_input)
    return LearnedSharedPrototypeTransducer(
        schema="tnlm-v3-learned-shared-prototype-transducer-v1",
        task_fingerprint=config.fingerprint(),
        value_cardinality=estimator_input.value_cardinality,
        cell_outputs=cell_outputs,
        coverage=coverage,
        observation_sha256=observation_sha256,
        supervision_source=supervision_source,
        canonical_state_supervision_assumed=True,
        universal_key_sharing_supplied=True,
        cyclic_law_supplied=False,
        used_heldout_labels_for_fit=False,
        automatic_hypothesis_selection_performed=False,
    )


def fit_shared_prototype_transducer(
    config: BindingTaskConfig,
    observations: Sequence[CanonicalPrototypeObservation],
    *,
    coverage: SharedPrototypeCoverage,
) -> LearnedSharedPrototypeTransducer:
    """Fit tables from externally supplied, sample-bound transition records.

    The public path requires the external-record origin tag; exact-executor
    controls use a separate wrapper and their unmodified rows are rejected
    here.  The tag is a caller attestation, not cryptographic authentication.
    """

    return _fit_shared_prototype_transducer_with_source(
        config,
        observations,
        coverage=coverage,
        supervision_source=CanonicalSupervisionSource.EXTERNAL_TRANSITION_RECORD,
    )


def generate_and_fit_shared_prototype_transducer(
    config: BindingTaskConfig,
    *,
    split: SeenSplit,
    seed: int,
    document_count: int,
    document_length: int,
    max_events: int = 1_000_000,
) -> LearnedSharedPrototypeTransducer:
    """Generate a direct-train oracle-state control and fit shared tables."""

    if type(config) is not BindingTaskConfig:
        raise TypeError("config must be exact BindingTaskConfig")
    if split != "train":
        raise ValueError("coefficient fitting requires split='train'")
    _plain_int("seed", seed, 0)
    _plain_int("document_count", document_count, 1)
    _plain_int("document_length", document_length, config.min_length)
    _plain_int("max_events", max_events, 1)
    if document_length > config.max_length:
        raise ValueError("document_length exceeds config.max_length")
    if document_count * document_length > max_events:
        raise AlgebraLearningLimitError("requested fit exceeds max_events")
    episodes = generate_binding_episodes(
        config,
        count=document_count,
        seed=seed,
        split=split,
        lengths=(document_length,) * document_count,
    )
    coverage = shared_prototype_coverage_from_episodes(
        config,
        episodes,
        split=split,
        seed=seed,
        document_length=document_length,
        max_events=max_events,
    )
    observations = _oracle_observations_from_validated_episodes(
        config,
        episodes,
        coverage,
    )
    return _fit_shared_prototype_transducer_with_source(
        config,
        observations,
        coverage=coverage,
        supervision_source=CanonicalSupervisionSource.EXACT_EXECUTOR_CONTROL,
    )


def evaluate_shared_prototype_transducer(
    config: ConfigLike,
    model: LearnedSharedPrototypeTransducer,
) -> SharedPrototypeFitEvaluation:
    """Compare fitted tables with the sealed exact algebra after fitting."""

    spec = _spec(config)
    if type(model) is not LearnedSharedPrototypeTransducer:
        raise TypeError("model must be exact LearnedSharedPrototypeTransducer")
    if model.value_cardinality != spec.value_cardinality:
        raise ValueError("model value cardinality does not match the task")
    if (
        type(config) is BindingTaskConfig
        and model.task_fingerprint != config.fingerprint()
    ):
        raise ValueError("model task fingerprint does not match the task")
    expected: dict[str, tuple[int, ...]] = {}
    for cell in shared_prototype_cells(spec):
        if cell.family == "update":
            if cell.transform is None:
                raise AssertionError("update cell lost its transform")
            value = (cell.source_value + cell.transform + 1) % spec.value_cardinality
        else:
            value = cell.source_value
        expected[cell.label] = _one_hot(value, spec.value_cardinality)
    actual = dict(model.cell_outputs)
    if set(actual) != set(expected):
        raise ValueError("model cell inventory does not match the task")
    exact = sum(actual[label] == target for label, target in expected.items())
    missing = sum(actual[label] is None for label in expected)
    all_exact = exact == len(expected)
    return SharedPrototypeFitEvaluation(
        schema="tnlm-v3-shared-prototype-fit-evaluation-v1",
        evaluated_cell_count=len(expected),
        exact_cell_count=exact,
        missing_cell_count=missing,
        all_value_tables_exact=all_exact,
        all_valid_programs_exact_given_supplied_state_contract=all_exact,
        heldout_semantics_used_only_for_postfit_evaluation=True,
    )


def sweep_shared_prototype_coverage(
    config: BindingTaskConfig,
    *,
    split: SeenSplit,
    seeds: Iterable[int],
    document_count: int,
    document_length: int,
    max_seeds: int = 10_000,
    max_total_events: int = 10_000_000,
) -> SharedPrototypeCoverageSweep:
    """Run an exact finite-sample rank sweep in deterministic seed order."""

    if type(config) is not BindingTaskConfig:
        raise TypeError("config must be exact BindingTaskConfig")
    _plain_int("max_seeds", max_seeds, 1)
    _plain_int("max_total_events", max_total_events, 1)
    _plain_int("document_count", document_count, 1)
    _plain_int("document_length", document_length, config.min_length)
    if document_length > config.max_length:
        raise ValueError("document_length exceeds config.max_length")
    try:
        seed_iterator = iter(seeds)
    except TypeError as error:
        raise TypeError("seeds must be iterable") from error
    seed_tuple = tuple(islice(seed_iterator, max_seeds + 1))
    if not seed_tuple:
        raise ValueError("seeds cannot be empty")
    if len(seed_tuple) > max_seeds:
        raise AlgebraLearningLimitError("seed count exceeds max_seeds")
    if any(type(seed) is not int or seed < 0 for seed in seed_tuple):
        raise TypeError("seeds must be exact nonnegative integers")
    if len(set(seed_tuple)) != len(seed_tuple):
        raise ValueError("seeds must be unique")
    total_events = len(seed_tuple) * document_count * document_length
    if total_events > max_total_events:
        raise AlgebraLearningLimitError("coverage sweep exceeds max_total_events")
    results = tuple(
        generate_shared_prototype_coverage(
            config,
            split=split,
            seed=seed,
            document_count=document_count,
            document_length=document_length,
            max_events=document_count * document_length,
        )
        for seed in seed_tuple
    )
    ranks = tuple(result.design_rank for result in results)
    return SharedPrototypeCoverageSweep(
        schema="tnlm-v3-shared-prototype-coverage-sweep-v1",
        task_fingerprint=config.fingerprint(),
        split=split,
        document_count=document_count,
        document_length=document_length,
        seeds=seed_tuple,
        full_rank_count=sum(result.full_rank for result in results),
        minimum_rank=min(ranks),
        maximum_rank=max(ranks),
        mean_rank=float(sum(ranks) / len(ranks)),
        results=results,
    )


def _shared_rank_with_exclusions(
    spec: BindingAlgebraSpec,
    excluded: frozenset[tuple[int, int]],
) -> int:
    """Rank of the supplied shared value-block design under pair exclusions."""

    values = spec.value_cardinality
    keys = spec.num_surface_keys
    observed_blocks = 0
    for value in range(values):
        available = [key for key in range(keys) if (key, value) not in excluded]
        if available:
            observed_blocks += 2  # bind and query
        if len(available) >= 2:
            observed_blocks += 1  # copy source/destination at this value
    for transform in range(values - 1):
        delta = transform + 1
        for source in range(values):
            target = (source + delta) % values
            if any(
                (key, source) not in excluded and (key, target) not in excluded
                for key in range(keys)
            ):
                observed_blocks += 1
    return observed_blocks * values


def pseudoheldout_fold_certificates(
    config: ConfigLike,
    *,
    max_folds: int = 10_000,
    max_rank_work: int = 1_000_000,
) -> tuple[PseudoheldoutFoldCertificate, ...]:
    """Certify shared-design rank for every seen pair used as an inner fold.

    This is a coverage certificate only.  It intentionally performs no model
    comparison or automatic hypothesis selection.
    """

    spec = _spec(config)
    _plain_int("max_folds", max_folds, 1)
    _plain_int("max_rank_work", max_rank_work, 1)
    if len(spec.heldout_key_value_pairs) != 1:
        raise ValueError("pseudoheldout analysis requires one real held-out pair")
    if spec.num_surface_keys < 2 or spec.max_live_bindings < 2:
        raise ValueError(
            "pseudoheldout shared-transducer analysis requires two live keys"
        )
    fold_count = spec.num_surface_keys * spec.value_cardinality - 1
    if fold_count > max_folds:
        raise AlgebraLearningLimitError("pseudoheldout analysis exceeds max_folds")
    rank_work = (
        fold_count
        * spec.num_surface_keys
        * spec.value_cardinality
        * spec.value_cardinality
    )
    if rank_work > max_rank_work:
        raise AlgebraLearningLimitError("pseudoheldout analysis exceeds max_rank_work")
    real = spec.heldout_key_value_pairs[0]
    parameter_count = shared_prototype_parameter_count(spec)
    result: list[PseudoheldoutFoldCertificate] = []
    for key in range(spec.num_surface_keys):
        for value in range(spec.value_cardinality):
            pair = (key, value)
            if pair == real:
                continue
            rank = _shared_rank_with_exclusions(spec, frozenset((real, pair)))
            result.append(
                PseudoheldoutFoldCertificate(
                    real_heldout_pair=real,
                    pseudoheldout_pair=pair,
                    supplied_shared_parameter_count=parameter_count,
                    supplied_shared_design_rank=rank,
                    supplied_shared_nullity=parameter_count - rank,
                    supplied_shared_identifies_pseudoheldout=rank == parameter_count,
                    automatic_hypothesis_selection_performed=False,
                )
            )
    return tuple(result)


def _hypothesis_rows(
    report: HeldoutIdentificationReport,
) -> tuple[HypothesisLearnability, ...]:
    unrestricted = report.unrestricted_system
    result = [
        HypothesisLearnability(
            hypothesis=LearningHypothesis.UNRESTRICTED_CANONICAL,
            parameter_count=unrestricted.total_parameter_count,
            constraint_rank=unrestricted.total_constraint_rank,
            nullity=unrestricted.total_nullity,
            heldout_behavior_identified_conditionally=False,
            canonical_state_supervision_assumed=True,
            universal_law_supplied=False,
            sharing_law_selected_from_data=False,
        )
    ]
    by_name = {row.hypothesis: row for row in report.structured_hypotheses}
    mappings = (
        (LearningHypothesis.KEY_LOCAL_BLOCKS, False),
        (LearningHypothesis.SHARED_UPDATE_COPY, True),
        (LearningHypothesis.FULL_SHARED_PROTOTYPES, True),
        (LearningHypothesis.PER_KEY_CYCLIC, True),
        (LearningHypothesis.SHARED_CYCLIC, True),
    )
    for hypothesis, law_supplied in mappings:
        row = by_name[hypothesis.value]
        result.append(
            HypothesisLearnability(
                hypothesis=hypothesis,
                parameter_count=row.parameter_count,
                constraint_rank=row.constraint_rank,
                nullity=row.nullity,
                heldout_behavior_identified_conditionally=(row.nullity == 0),
                canonical_state_supervision_assumed=True,
                universal_law_supplied=law_supplied,
                sharing_law_selected_from_data=False,
            )
        )
    return tuple(result)


def _report_payload(report: AlgebraLearnabilityReport) -> dict[str, object]:
    return {
        "schema": report.schema,
        "task_fingerprint": report.task_fingerprint,
        "heldout_pair": list(report.heldout_pair),
        "state_counts": [report.full_state_count, report.train_state_count],
        "feature_ranks": [report.full_feature_rank, report.train_feature_rank],
        "passive_unrestricted_nullity": report.passive_unrestricted_nullity,
        "passive_uniform_recovery_possible": report.passive_uniform_recovery_possible,
        "zero_support_identical_likelihood_witness_exists": (
            report.zero_support_identical_likelihood_witness_exists
        ),
        "one_separating_membership_probe": list(report.one_separating_membership_probe),
        "hypotheses": [
            {
                "hypothesis": row.hypothesis.value,
                "parameters": row.parameter_count,
                "rank": row.constraint_rank,
                "nullity": row.nullity,
                "conditional_identification": (
                    row.heldout_behavior_identified_conditionally
                ),
                "canonical_state_supervision": row.canonical_state_supervision_assumed,
                "universal_law_supplied": row.universal_law_supplied,
                "sharing_law_selected": row.sharing_law_selected_from_data,
            }
            for row in report.hypotheses
        ],
        "pseudoheldout_folds": [
            {
                "real": list(row.real_heldout_pair),
                "pseudo": list(row.pseudoheldout_pair),
                "parameters": row.supplied_shared_parameter_count,
                "rank": row.supplied_shared_design_rank,
                "nullity": row.supplied_shared_nullity,
            }
            for row in report.pseudoheldout_folds
        ],
        "automatic_hypothesis_selection_performed": (
            report.automatic_hypothesis_selection_performed
        ),
        "sequence_only_representation_learning_performed": (
            report.sequence_only_representation_learning_performed
        ),
    }


def analyze_algebra_learnability(
    config: ConfigLike,
    *,
    max_states: int = 1_000_000,
    max_permutations: int = 100_000,
) -> AlgebraLearnabilityReport:
    """Return the exact passive and conditional learnability boundary."""

    spec = _spec(config)
    identification = analyze_heldout_identification(
        spec,
        max_states=max_states,
        max_permutations=max_permutations,
    )
    folds = pseudoheldout_fold_certificates(spec)
    fields = {
        "schema": "tnlm-v3-algebra-learnability-v1",
        "task_fingerprint": _task_fingerprint(config),
        "heldout_pair": identification.heldout_pair,
        "full_state_count": identification.full_state_count,
        "train_state_count": identification.train_state_count,
        "full_feature_rank": identification.full_feature_rank,
        "train_feature_rank": identification.train_feature_rank,
        "passive_unrestricted_nullity": (
            identification.unrestricted_system.total_nullity
        ),
        "passive_uniform_recovery_possible": False,
        "zero_support_identical_likelihood_witness_exists": True,
        "one_separating_membership_probe": (
            f"BIND({identification.heldout_pair[0]},{identification.heldout_pair[1]})",
            f"QUERY({identification.heldout_pair[0]})",
        ),
        "hypotheses": _hypothesis_rows(identification),
        "pseudoheldout_folds": folds,
        "automatic_hypothesis_selection_performed": False,
        "sequence_only_representation_learning_performed": False,
    }
    payload = _report_payload(SimpleNamespace(**fields))
    digest = hashlib.sha256(
        json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()
    return AlgebraLearnabilityReport(**fields, report_sha256=digest)


__all__ = [
    "AlgebraLearnabilityReport",
    "AlgebraLearningLimitError",
    "CanonicalPrototypeObservation",
    "CanonicalSupervisionSource",
    "HypothesisLearnability",
    "LearningHypothesis",
    "LearnedSharedPrototypeTransducer",
    "PrototypeCell",
    "PseudoheldoutFoldCertificate",
    "SharedPrototypeCoverage",
    "SharedPrototypeCoverageSweep",
    "SharedPrototypeFitEvaluation",
    "analyze_algebra_learnability",
    "evaluate_shared_prototype_transducer",
    "fit_shared_prototype_transducer",
    "generate_and_fit_shared_prototype_transducer",
    "generate_shared_prototype_coverage",
    "pseudoheldout_fold_certificates",
    "oracle_canonical_observations_from_episodes",
    "shared_prototype_cells",
    "shared_prototype_coverage_from_episodes",
    "shared_prototype_parameter_count",
    "sweep_shared_prototype_coverage",
]
